module.exports = {
  config: {
    name: "war", // name of the command
    description: "Send all Tagalog trash talk messages one by one", // description of the command
    usage: "{prefix}war", // usage of the command
    cooldown: 5, // a cooldown for the command (default is 5 seconds)
    accessableby: 2, // 0 is for everyone
    category: "Fun", // category of the command
    prefix: true, // true if the command needs a prefix
  },
  start: async function ({ api, text, react, event, reply }) {
    // Array of 200 Tagalog trash talk messages
    const trashTalks = [
      "Huwag kang magmalinis, hindi ka sabon.",
      "Kung ako sa'yo, titigil na ako, kasi wala ka naman talagang laban.",
      "Ang tanga mo, sinayang mo lang oras ko.",
      "Parang WiFi signal ka, nawawala pag kailangan.",
      "Ang kapal ng mukha mo, kailangan na ng bulldozer para tanggalin.",
      "Mas marami ka pang drama kaysa sa teleserye.",
      "Huwag kang umasa, hindi ka makakapasok sa utak ko.",
      "Yung utak mo parang 3G, mabagal na nga, outdated pa.",
      "Parang multo ka, wala kang presence pero nakaka-asar.",
      "Huwag kang magpanggap na matalino kung Google ka lang naman magaling.",
      "Suntok lang ang kaya mo, pero utak mo kulang sa bato.",
      "Mas malakas pa ata ang hangin ng electric fan kaysa sa talino mo.",
      "Walang ganyanan, baka mapikon ka, eh hindi naman bagay sa’yo ang drama.",
      "Parang utang, lagi kang nagpaparamdam pero hindi mo kayang bayaran.",
      "Kung babasahin ang utak mo, baka kulang pa sa isang paragraph.",
      "Kahit anong gawin mong porma, mukha ka pa ring kawawa.",
      "Mas mataas pa ang electric bill ko kaysa IQ mo.",
      "Kung slow ka pa sa internet, mas mabagal ka pa sa pag-iisip.",
      "Para kang internet connection sa probinsya, puro loading.",
      "Huwag kang umasta na parang milyonaryo, kasi mukhang utang lang alam mo.",
      "Parang break-up lang, hindi mo kinaya.",
      "Akala ko ba matalino ka? Nasaan?",
      "Mas mabilis pa ang kumurap kaysa sa utak mo.",
      "Kahit gaano kalaki ang bibig mo, hindi mo kayang ipaliwanag ang katangahan mo.",
      "Ang astig mo naman, kaya lang sa imagination lang.",
      "Para kang pako, nakakatusok, pero walang halaga.",
      "Ang dami mong salita, pero wala namang laman.",
      "Kung hangin ka, wala ka na sigurong oxygen.",
      "Laging ikaw ang bida sa kwento mo, kahit hindi naman totoo.",
      "Kahit pusa may siyam na buhay, pero ikaw hanggang dalawa lang ang utak mo.",
      "Bobo ka na nga, mayabang ka pa.",
      "Ang buhay mo parang isang teleserye, walang kwenta.",
      "Ikaw lang yata ang taong nasisikipan sa maluwang.",
      "Ang talino mo yata, pang-kindergarten lang.",
      "Mas matalino pa yata yung aso ko kaysa sa'yo.",
      "Akala mo siguro sikat ka, pero sa barangay lang.",
      "Bakit nga pala wala kang utak? Naiwan mo ba sa bahay?",
      "Huwag kang magpanggap na busy, wala ka naman talagang ginagawa.",
      "Para kang sirang plaka, paulit-ulit pero walang kwenta.",
      "Laging kang galit, pero walang saysay.",
      "Ang yabang mo, pero wala ka namang ambag sa buhay.",
      "Huwag ka nang magtaka kung bakit wala kang kaibigan, kasi wala kang kwenta.",
      "Mas mabilis pa ata ang pila sa SSS kaysa sa pag-iisip mo.",
      "Kung utak lang ang puhunan, bankrup ka na.",
      "Akala ko masama ang loob mo, yun pala wala ka lang utak.",
      "Mas mabagal pa utak mo kaysa sa trapik sa EDSA.",
      "Kahit anong gawin mong porma, hindi mo kayang itago ang katangahan mo.",
      "Para kang flashlight, umiilaw ka lang kapag may power.",
      "Wala kang pinagkaiba sa basurahan, kasi lahat ng sinasabi mo basura.",
      "Kahit saan ka magpunta, dala mo pa rin ang kahinaan mo.",
      "Lakas ng loob mong mag-comment, pero wala ka namang alam.",
      "Kung trophy ang katangahan, panalo ka na.",
      "Ikaw ang dahilan kung bakit may salitang 'bobo'.",
      "Kung sipag ang labanan, natutulog ka pa rin.",
      "Para kang tsismis, walang kwenta pero pinapansin.",
      "Kung hangin lang ang utak, sana nag-drift ka na lang sa kawalan.",
      "Para kang joke na hindi nakakatawa.",
      "Mas marami pa akong natutunan sa cartoons kaysa sa'yo.",
      "Ikaw yung tipo ng tao na dapat sinasanay nang hindi pinapansin.",
      "Huwag kang magtanong kung bakit ka nag-iisa, kasi walang may gustong kasama ka.",
      "Kung bobo ka, tanggapin mo na lang.",
      "Ang utak mo parang traffic light na walang ilaw, hindi alam kung saan pupunta.",
      "Para kang cellphone na walang signal, useless.",
      "Kung may award para sa katangahan, panalo ka na agad.",
      "Ikaw yung tipong kahit sa PBB hindi papasa.",
      "Mas may kwenta pa ang ants kaysa sa'yo.",
      "Kung lalaban ka, siguraduhin mong hindi ka talunan.",
      "Ang buhay mo parang gitna ng donut, wala.",
      "Mas makulit ka pa sa lamok.",
      "Kung utak lang ang labanan, bagsak ka na.",
      "Kung sipag lang, wala ka na sa listahan.",
      "Wala kang pinagkaiba sa basura, kasi wala kang kwenta.",
      "Ang bilis mong magyabang, pero wala ka namang ibubuga.",
      "Kung pasensya lang, ubos na ako sa'yo.",
      "Kahit saan ka magpunta, dala mo pa rin ang kabobohan mo.",
      "Ikaw yung tipo ng tao na walang ambag sa buhay.",
      "Ang yabang mo, pero wala kang ginawa.",
      "Ang dami mong sinasabi, pero wala ka namang ginagawa.",
      "Huwag kang mag-alala, sanay na ako sa kabobohan mo.",
      "Mas marami pa akong natutunan sa aso ko kaysa sa'yo.",
      "Para kang assignment na walang sagot, walang kwenta.",
      "Kung may exam para sa katangahan, perfect ka na.",
      "Wala kang pinagkaiba sa slow internet, nakakainis.",
      "Kahit anong gawin mo, wala kang maipapakita.",
      "Walang saysay ang buhay mo, parang kwentong barbero.",
      "Huwag kang magpanggap na masipag, kasi tamad ka naman talaga.",
      "Wala kang silbi, parang papel na walang sulat.",
      "Kung talent ang yabang, ikaw na ang bida.",
      "Mas marami pa akong natutunan sa isang bato kaysa sa'yo.",
      "Kung tanga ang labanan, ikaw na ang panalo.",
      "Kung diploma ang yabang, cum laude ka na.",
      "Mas mabilis pa ang delivery sa online shop kaysa sa pag-iisip mo.",
      "Kung bobo ka, tanggapin mo na lang.",
      "Mas marami pa akong natutunan sa kapatid kong bata kaysa sa'yo.",
      "Para kang back subject, hindi ka na dapat pinapansin.",
      "Kung yabang lang, ikaw na ang hari.",
      "Kung paligsahan ng katangahan, ikaw na ang champion.",
      "Minsan, nakakahiya ka na sa sarili mo.",
      "Bakit hindi ka nalang magtago sa ilalim ng lupa?",
      "Parang sponge, absorb ka lang ng absorb pero walang contribution.",
      "Ang dami mong oras na nasasayang sa pagiging useless.",
      "Kung baka nga ayaw sayo ng magulang mo, ako pa kaya.",
      "Sa dami ng sinasabi mo, parang hindi mo alam ang pinag-uusapan mo.",
      "Baka kailangan mo ng manual para sa utak mo.",
      "Wala kang ibang alam kundi magpanggap.",
      "Mas bobo ka pa kaysa sa basurahan.",
      "Kung ang tanga ay kulay, ikaw ang rainbow.",
      "Wala kang kwenta, parang hindi ka nag-exist.",
      "Baka kailangan mo ng GPS para malaman ang tamang direksyon.",
      "Parang sponge bob ka, puro barkada pero walang laman.",
      "Kung kilig ang labanan, ikaw na ang hari ng kawalang laman.",
      "Minsan, isipin mo na lang na hindi ka tao.",
      "Ikaw yung tipong kahit sa buong mundo, hindi ka magagamit.",
      "Kung ang pagiging bobo ay negosyo, ikaw na ang CEO.",
      "Walang pwedeng ipagmalaki sa'yo, maliban sa pagiging walang kwenta.",
      "Parang vacuum ka, puro hangin pero walang kabuluhan.",
      "Kung ang pagiging inutil ay art, ikaw na ang maestro.",
      "Minsan naiisip ko, baka may special talent ka sa pagiging bobo.",
      "Ikaw yung klase ng tao na walang ambisyon sa buhay.",
      "Kung ang kasabihan ay ‘madaming alam’, ikaw ang ‘madaming walang alam’.",
      "Ang tanga mo, kung magta-tanong ka pa, baka lalo pang bumagsak.",
      "Kahit anong gawin mo, palaging mali.",
      "Sa lahat ng ginagawa mo, hindi ka pa rin nakakabawi sa pagiging useless.",
      "Parang robot ka, walang emosyon, puro function.",
      "Kung tanga ang labanan, ikaw na ang reyna.",
      "Mas marami pang saysay ang isang papel kaysa sa'yo.",
      "Kahit anong sabihin mo, wala ka namang impact.",
      "Baka kailangan mo ng coach para turuan ka kung paano mag-isip.",
      "Ang brain cells mo, parang dumi ng isda.",
      "Kung ang utak ay isang laro, ikaw na ang laging talo.",
      "Mas malakas pa ang ulan kaysa sa ideya mo.",
      "Kahit anong gawin mo, walang kwenta.",
      "Sa pagiging bobo mo, parang may sariling kategorya.",
      "Kung ang pagiging walang silbi ay sports, ikaw ang gold medalist.",
      "Bakit hindi ka magpa-assist sa iba para hindi magmukhang tanga?",
      "Kahit anong pilit mo, hindi ka magiging useful.",
      "Wala kang kwenta kahit anong gawin mo.",
      "Kung walang brain cells ang labanan, ikaw na ang champion.",
      "Minsan naiisip ko, baka may dahilan kung bakit walang pumapansin sa'yo.",
      "Kung ang pagiging inutil ay halo-halo, ikaw na ang super mix.",
      "Sa sobrang tanga mo, baka kailangan mo ng special assistance.",
      "Baka kailangan mo ng manual para malaman kung paano maging tao.",
      "Ang buhay mo parang rerun ng isang telenovela, walang bago.",
      "Walang impact ang mga sinasabi mo, parang hangin lang.",
      "Kung ang pagiging walang kwenta ay award, ikaw na ang winner.",
      "Para kang sponge, absorb ka lang ng absorb pero wala pang naibibigay.",
      "Kahit anong gawin mo, palaging walang resulta.",
      "Kung ang pagiging walang saysay ay sine, ikaw ang main character.",
      "Kung ang pagiging useless ay anino, ikaw ang pinakamalaking anino.",
      "Kung hindi ka magbabago, baka kailangan mo nang bumalik sa basics.",
      "Ang utak mo parang putik, madumi at walang halaga.",
      "Walang kapaki-pakinabang ang mga sinasabi mo.",
      "Kung ang pagiging walang silbi ay pamagat ng libro, ikaw na ang bestseller.",
      "Kung ang pagiging bobo ay matalino, ikaw na ang Einstein.",
      "Ang talino mo parang isang balde ng tubig, walang saysay.",
      "Kahit anong gawin mo, hindi mo kayang baguhin ang pagiging inutil mo.",
      "Baka kailangan mo ng bagong pag-aaral para mag-improve.",
      "Kung ang pagiging walang kwenta ay kalakaran, ikaw na ang mangunguna.",
      "Walang makikita sa'yo maliban sa pagiging walang ambag.",
      "Kahit anong gawin mo, palaging walang resulta.",
      "Kung ang pagiging bobo ay isang paraan ng pamumuhay, ikaw na ang pinakamagaling.",
      "Ang utak mo parang itlog, wala kang ibubuga.",
      "Kung ang pagiging walang kwenta ay isang paligsahan, ikaw na ang nanalo.",
      "Para kang sakit sa ulo, wala kang silbi.",
      "Baka kailangan mo ng dagdag na tulong para hindi magmukhang tanga.",
      "Ang pagiging inutil mo parang isang diary, walang laman.",
      "Kung ang pagiging bobo ay isang laro, ikaw na ang grand champion.",
      "Kahit anong gawin mo, hindi ka pa rin magiging kapaki-pakinabang.",
      "Ang tanga mo parang isang sirang relo, palaging mali.",
      "Kung ang pagiging walang kwenta ay isang negosyo, ikaw na ang boss.",
      "Minsan naiisip ko kung anong klaseng tao ka.",
      "Ang buhay mo parang isang comic strip, walang katuturan.",
      "Kung ang pagiging bobo ay isang diyos, ikaw na ang pinakamas mataas.",
      "Walang dapat ipagmalaki sa pagiging useless mo.",
      "Kahit anong gawin mo, hindi mo mababago ang pagiging tanga mo.",
      "Kung ang pagiging walang kwenta ay isang pelikula, ikaw na ang bida.",
      "Para kang salamin na walang reflection, walang saysay.",
      "Ang talino mo parang pusit, walang kwenta.",
      "Kahit anong gawin mo, palaging walang epekto.",
      "Kung ang pagiging bobo ay isang laro, ikaw na ang champion.",
      "Sa sobrang bobo mo, parang hindi ka makaka-move on.",
      "Baka kailangan mo ng bagong paraan para makapag-isip.",
      "Kung ang pagiging walang kwenta ay isang award, ikaw na ang winner.",
      "Kung ang pagiging bobo ay isang sining, ikaw na ang artist.",
      "Para kang sitcom, walang bago pero patuloy na pinapanood.",
      "Kung ang pagiging bobo ay isang kakayahan, ikaw na ang master.",
      "Minsan naiisip ko, baka may dahilan kung bakit walang pumapansin sa'yo.",
      "Kung ang pagiging walang kwenta ay pamagat ng libro, ikaw na ang bestseller.",
      "Ang pagiging bobo mo parang isang walang laman na libro.",
      "Kahit anong gawin mo, hindi mo maaalis ang pagiging walang kwenta mo.",
      "Kung ang pagiging walang kwenta ay isang talento, ikaw na ang superstar.",
      "Baka kailangan mo ng tulong para hindi magmukhang tanga.",
      "Kung ang pagiging bobo ay isang kalakaran, ikaw na ang mangunguna.",
      "Ang buhay mo parang isang sirang plaka, paulit-ulit na walang saysay.",
      "Kahit anong gawin mo, wala kang makakamtan.",
      "Kung ang pagiging walang kwenta ay isang pagtatanghal, ikaw na ang lead actor.",
      "Para kang isang lumang paborito, wala nang saysay.",
      "Ang pagiging bobo mo parang isang sirang relo, palaging mali.",
      "Minsan naiisip ko, baka kailangan mo ng bagong tao para magbigay sa'yo ng feedback.",
      "Kahit anong gawin mo, wala kang maipapakita.",
      "Kung ang pagiging walang kwenta ay isang anyo ng sining, ikaw na ang master.",
      "Sa sobrang bobo mo, parang hindi ka makaka-move on.",
      "Kung ang pagiging walang kwenta ay isang negosyo, ikaw na ang CEO.",
      "Baka kailangan mo ng pagbabago para hindi magmukhang tanga.",
      "Kung ang pagiging bobo ay isang sining, ikaw na ang artista.",
      "Ang pagiging bobo mo parang isang sirang makina, walang ginagawa.",
      "Kahit anong gawin mo, wala kang makakamtan.",
      "Kung ang pagiging walang kwenta ay isang pagganap, ikaw na ang lead.",
      "Para kang isang lumang serye, walang bago pero patuloy na pinapanood.",
      "Ang pagiging bobo mo parang isang sirang plaka, paulit-ulit na walang saysay.",
      "Ikaw yung tipong kahit sa buong mundo, hindi ka magagamit.",
      "Kung ang pagiging bobo ay negosyo, ikaw na ang CEO.",
      "Walang pwedeng ipagmalaki sa'yo, maliban sa pagiging walang kwenta.",
      "Parang vacuum ka, puro hangin pero walang kabuluhan.",
      "Kung ang pagiging inutil ay art, ikaw na ang maestro.",
      "Minsan naiisip ko, baka may special talent ka sa pagiging bobo.",
      "Ikaw yung klase ng tao na walang ambisyon sa buhay.",
      "Kung ang kasabihan ay ‘madaming alam’, ikaw ang ‘madaming walang alam’.",
      "Ang tanga mo, kung magta-tanong ka pa, baka lalo pang bumagsak.",
      "Kahit anong gawin mo, palaging mali.",
      "Sa lahat ng ginagawa mo, hindi ka pa rin nakakabawi sa pagiging useless.",
      "Parang robot ka, walang emosyon, puro function.",
      "Kung tanga ang labanan, ikaw na ang reyna.",
      "Mas marami pang saysay ang isang papel kaysa sa'yo.",
      "Kahit anong sabihin mo, wala ka namang impact.",
      "Baka kailangan mo ng coach para turuan ka kung paano mag-isip.",
      "Ang brain cells mo, parang dumi ng isda.",
      "Kung ang utak ay isang laro, ikaw na ang laging talo.",
      "Mas malakas pa ang ulan kaysa sa ideya mo.",
      "Kahit anong gawin mo, walang kwenta.",
      "Sa pagiging bobo mo, parang may sariling kategorya.",
      "Kung ang pagiging walang silbi ay sports, ikaw ang gold medalist.",
      "Bakit hindi ka magpa-assist sa iba para hindi magmukhang tanga?",
      "Kahit anong pilit mo, hindi ka magiging useful.",
      "Wala kang kwenta kahit anong gawin mo.",
      "Kung walang brain cells ang labanan, ikaw na ang champion.",
      "Minsan naiisip ko, baka may dahilan kung bakit walang pumapansin sa'yo.",
      "Kung ang pagiging inutil ay halo-halo, ikaw na ang super mix.",
      "Sa sobrang tanga mo, baka kailangan mo ng special assistance.",
      "Baka kailangan mo ng manual para malaman kung paano maging tao.",
      "Ang buhay mo parang rerun ng isang telenovela, walang bago.",
      "Walang impact ang mga sinasabi mo, parang hangin lang.",
      "Kung ang pagiging walang kwenta ay award, ikaw na ang winner.",
      "Para kang sponge, absorb ka lang ng absorb pero wala pang naibibigay.",
      "Kahit anong gawin mo, palaging walang resulta.",
      "Kung ang pagiging walang saysay ay sine, ikaw ang main character.",
      "Kung ang pagiging useless ay anino, ikaw ang pinakamalaking anino.",
      "Kung hindi ka magbabago, baka kailangan mo nang bumalik sa basics.",
      "Ang utak mo parang putik, madumi at walang halaga.",
      "Walang kapaki-pakinabang ang mga sinasabi mo.",
      "Kung ang pagiging walang silbi ay pamagat ng libro, ikaw na ang bestseller.",
      "Kung ang pagiging bobo ay matalino, ikaw na ang Einstein.",
      "Ang talino mo parang isang balde ng tubig, walang saysay.",
      "Kahit anong gawin mo, hindi mo kayang baguhin ang pagiging inutil mo.",
      "Baka kailangan mo ng bagong pag-aaral para mag-improve.",
      "Kung ang pagiging walang kwenta ay kalakaran, ikaw na ang mangunguna.",
      "Walang makikita sa'yo maliban sa pagiging walang ambag.",
      "Kahit anong gawin mo, palaging walang resulta.",
      "Kung ang pagiging bobo ay isang paraan ng pamumuhay, ikaw na ang pinakamagaling.",
      "Ang utak mo parang itlog, wala kang ibubuga.",
      "Kung ang pagiging walang kwenta ay isang paligsahan, ikaw na ang nanalo.",
      "Para kang sakit sa ulo, wala kang silbi.",
      "Baka kailangan mo ng dagdag na tulong para hindi magmukhang tanga.",
      "Ang pagiging inutil mo parang isang diary, walang laman.",
      "Kung ang pagiging bobo ay isang laro, ikaw na ang grand champion.",
      "Kahit anong gawin mo, hindi ka pa rin magiging kapaki-pakinabang.",
      "Ang tanga mo parang isang sirang relo, palaging mali.",
      "Kung ang pagiging walang kwenta ay isang negosyo, ikaw na ang boss.",
      "Minsan naiisip ko kung anong klaseng tao ka.",
      "Ang buhay mo parang isang comic strip, walang katuturan.",
      "Kung ang pagiging bobo ay isang diyos, ikaw na ang pinakamas mataas.",
      "Walang dapat ipagmalaki sa pagiging useless mo.",
      "Kahit anong gawin mo, hindi mo mababago ang pagiging tanga mo.",
      "Kung ang pagiging walang kwenta ay isang pelikula, ikaw na ang bida.",
      "Para kang salamin na walang reflection, walang saysay.",
      "Ang talino mo parang pusit, walang kwenta.",
      "Kahit anong gawin mo, palaging walang epekto.",
      "Kung ang pagiging bobo ay isang laro, ikaw na ang champion.",
      "Sa sobrang bobo mo, parang hindi ka makaka-move on.",
      "Baka kailangan mo ng bagong paraan para makapag-isip.",
      "Kung ang pagiging walang kwenta ay isang award, ikaw na ang winner.",
      "Kung ang pagiging bobo ay isang sining, ikaw na ang artist.",
      "Para kang sitcom, walang bago pero patuloy na pinapanood.",
      "Kung ang pagiging bobo ay isang kakayahan, ikaw na ang master.",
      "Minsan naiisip ko, baka may dahilan kung bakit walang pumapansin sa'yo.",
      "Kung ang pagiging walang kwenta ay pamagat ng libro, ikaw na ang bestseller.",
      "Ang pagiging bobo mo parang isang walang laman na libro.",
      "Kahit anong gawin mo, hindi mo maaalis ang pagiging walang kwenta mo.",
      "Kung ang pagiging walang kwenta ay isang talento, ikaw na ang superstar.",
      "Baka kailangan mo ng tulong para hindi magmukhang tanga.",
      "Kung ang pagiging bobo ay isang kalakaran, ikaw na ang mangunguna.",
      "Ang buhay mo parang isang sirang plaka, paulit-ulit na walang saysay.",
      "Kahit anong gawin mo, wala kang makakamtan.",
      "Kung ang pagiging walang kwenta ay isang pagtatanghal, ikaw na ang lead actor.",
      "Para kang isang lumang paborito, wala nang saysay.",
      "Ang pagiging bobo mo parang isang sirang relo, palaging mali.",
      "Minsan naiisip ko, baka kailangan mo ng bagong tao para magbigay sa'yo ng feedback.",
      "Kahit anong gawin mo, wala kang maipapakita.",
      "Kung ang pagiging walang kwenta ay isang anyo ng sining, ikaw na ang master.",
      "Sa sobrang bobo mo, parang hindi ka makaka-move on.",
      "Kung ang pagiging walang kwenta ay isang negosyo, ikaw na ang CEO.",
      "Baka kailangan mo ng pagbabago para hindi magmukhang tanga.",
      "Kung ang pagiging bobo ay isang sining, ikaw na ang artista.",
      "Ang pagiging bobo mo parang isang sirang makina, walang ginagawa.",
      "Kahit anong gawin mo, wala kang makakamtan.",
      "Kung ang pagiging walang kwenta ay isang pagganap, ikaw na ang lead.",
      "Para kang isang lumang serye, walang bago pero patuloy na pinapanood.",
      "Ang pagiging bobo mo parang isang sirang plaka, paulit-ulit na walang saysay.",
      "Kahit anong gawin mo, hindi ka pa rin magiging kapaki-pakinabang.",
      "Kung ang pagiging walang kwenta ay isang libangan, ikaw na ang pinakamasaya.",
      "Kung ang pagiging bobo ay isang laro, ikaw na ang best player.",
      "Para kang isang sirang radyo, puro static.",
      "Kahit anong gawin mo, hindi mo mababago ang pagiging bobo mo.",
      "Kung ang pagiging walang kwenta ay isang event, ikaw na ang guest of honor.",
      "Minsan naiisip ko kung anong klaseng tao ka.",
      "Ang pagiging bobo mo parang isang walang laman na kuwento.",
      "Kahit anong gawin mo, wala kang maipapakita.",
      "Kung ang pagiging walang kwenta ay isang award, ikaw na ang nanalo.",
      "Sa sobrang bobo mo, parang hindi ka magagamit sa kahit anong aspeto.",
      "Kung ang pagiging bobo ay isang kasanayan, ikaw na ang master.",
      "Kahit anong gawin mo, wala kang makakamtan.",
      "Kung ang pagiging walang kwenta ay isang sining, ikaw na ang artista.",
      "Baka kailangan mo ng tulong para hindi magmukhang tanga.",
      "Kung ang pagiging bobo ay isang kasanayan, ikaw na ang master.",
      "Para kang isang sirang radio, puro static.",
      "Ang pagiging bobo mo parang isang walang laman na diary.",
      "Kahit anong gawin mo, wala kang maipapakita.",
      "Kung ang pagiging walang kwenta ay isang anyo ng sining, ikaw na ang pinakamahusay.",
    // Add all other messages here up to 200
    ];

    // Function to send messages one by one with delay
    const sendMessages = async () => {
      for (const message of trashTalks) {
        await reply(message); // Send the message
        await new Promise(resolve => setTimeout(resolve, 5000)); // Wait for 5 seconds
      }
    };

    // React with an emoji (optional)
    await react("💥");

    // Start sending messages
    sendMessages();
  }
};
